/** Configuration fields shared by the Host schema and settings card. */
export const MAX_TIMER_DELAY_MS = 2_147_483_647

/** Stable settings namespace used by both Host and browser halves. */
export const SETTINGS_NAMESPACE = 'ptc-plus'

/**
 * Ordered field definitions for the plugin configuration card. `label` and
 * `description` are the canonical Host schema copy; `labelEn` and
 * `descriptionEn` carry the English settings-card copy. A field's description
 * exists in both locales or in neither.
 */
export const CONFIG_FIELDS = Object.freeze([
  {
    key: 'enabled',
    type: 'boolean',
    default: true,
    label: '启用 PTC Plus',
    labelEn: 'Enable PTC Plus',
    description: '',
    descriptionEn: '',
  },
  {
    key: 'enhancedToolView',
    type: 'boolean',
    default: true,
    label: '使用 PTC Plus 增强工具卡片',
    labelEn: 'Use enhanced PTC Plus tool cards',
    description: '开启时使用 PTC Plus 工具卡片；关闭后使用 DSH 原生 run_code 和 edit_run_code 工具卡片。',
    descriptionEn: 'When enabled, PTC Plus renders the tool cards; when disabled, run_code and edit_run_code use DSH native tool cards.',
  },
  {
    key: 'autoDescribeRunCode',
    type: 'boolean',
    default: true,
    label: '自动补全缺失的 run_code 摘要',
    labelEn: 'Auto-fill missing run_code summaries',
    description: '执行时宽容缺少外层摘要的 run_code 调用并生成固定 UI 摘要；不改变模型请求、原始调用参数、代码或嵌套 native 工具参数。',
    descriptionEn: 'Tolerates a missing outer run_code summary during execution and generates a fixed UI summary without changing the model request, original call arguments, code, or nested native-tool arguments.',
  },
  {
    key: 'canonicalizeToolCalls',
    type: 'boolean',
    default: true,
    label: '修复可识别的顶层 native 工具误调用',
    labelEn: 'Repair recognizable top-level native tool mis-calls',
    description: '仅当当前 schema 能唯一确认目标工具且参数有效时，修复顶层 native 工具误调用。',
    descriptionEn: 'Repairs a top-level native tool mis-call only when the current schema uniquely identifies the target and validates its arguments.',
  },
  {
    key: 'cordisToolsEnabled',
    type: 'boolean',
    default: false,
    label: '在 PTC 模式中启用官方 Cordis 工具',
    labelEn: 'Enable official Cordis tools in PTC mode',
    description: '开启后，PTC agent 可使用官方 Cordis 工具、配套指引和开发 Skill；关闭后移除这些能力。Cordis 工具以 DSH 进程权限运行。',
    descriptionEn: 'When enabled, PTC agents can use the official Cordis tools, guidance, and development Skill; disabling removes them. Cordis tools run with the DSH process permissions.',
  },
  {
    key: 'looseTopLevelRedeclarations',
    type: 'boolean',
    default: true,
    label: '允许顶层变量重声明',
    labelEn: 'Allow top-level variable redeclarations',
    description: '允许顶层 const 或 let 声明替换已有变量；关闭后，重声明会在执行前被拒绝。',
    descriptionEn: 'Allows top-level const or let declarations to replace existing variables; disabling rejects redeclarations before execution.',
  },
  {
    key: 'autoRewriteImports',
    type: 'boolean',
    default: true,
    label: '支持静态 import 声明',
    labelEn: 'Support static import declarations',
    description: '允许在 run_code 中使用静态 import，并保留模块解析和只读 binding 语义。',
    descriptionEn: 'Allows static import declarations in run_code while preserving module resolution and read-only binding semantics.',
  },
  {
    key: 'autoStripExports',
    type: 'boolean',
    default: true,
    label: '支持顶层 export 修饰符',
    labelEn: 'Support top-level export modifiers',
    description: '允许在 run_code 中使用顶层 export，并保留对应的本地声明或模块副作用。',
    descriptionEn: 'Allows top-level export syntax in run_code while preserving the corresponding local declaration or module side effect.',
  },
  {
    key: 'autoSplitRedeclarations',
    type: 'boolean',
    default: true,
    label: '支持混合解构重声明',
    labelEn: 'Support mixed destructuring redeclarations',
    description: '允许顶层解构声明同时包含新变量和已有变量。',
    descriptionEn: 'Allows top-level destructuring declarations to contain both new and existing variables.',
  },
  {
    key: 'durableReplay',
    type: 'boolean',
    default: true,
    label: '启用持久 REPL 恢复',
    labelEn: 'Enable durable REPL recovery',
    description: 'worker 重启后从 session journal 重建可恢复的 REPL 状态。',
    descriptionEn: 'Rebuilds recoverable REPL state from the session journal after a worker restart.',
  },
  {
    key: 'tipsEnabled',
    type: 'boolean',
    default: true,
    label: '启用失败恢复提示',
    labelEn: 'Enable failure recovery tips',
    description: '在符合条件的失败后显示有冷却间隔的恢复提示。',
    descriptionEn: 'Shows recovery tips with a cooldown after qualifying failures.',
  },
  {
    key: 'computeMs',
    type: 'integer',
    default: 60_000,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '单 cell CPU 时间上限 (ms)',
    labelEn: 'CPU time limit per cell (ms)',
    description: '同步计算超过该上限时中断当前 cell。',
    descriptionEn: 'Interrupts the current cell when synchronous computation exceeds this limit.',
  },
  {
    key: 'maxWallMs',
    type: 'integer',
    default: 600_000,
    min: 1,
    max: MAX_TIMER_DELAY_MS,
    label: '单 cell 总耗时上限 (ms)',
    labelEn: 'Elapsed time limit per cell (ms)',
    description: '限制完整 cell 执行的耗时，包括异步等待。',
    descriptionEn: 'Limits the complete cell execution time, including asynchronous waits.',
  },
  {
    key: 'maxOldGenerationSizeMb',
    type: 'integer',
    default: 512,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '每个 worker 旧生代内存上限 (MiB)',
    labelEn: 'Old-generation memory limit per worker (MiB)',
    description: '限制每个 worker 的 V8 旧生代；活动 worker 存在时不能修改。',
    descriptionEn: 'Limits the V8 old generation for each worker; this setting cannot change while a worker is active.',
  },
  {
    key: 'maxNestedRunCodeDepth',
    type: 'integer',
    default: 8,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: 'code.run 嵌套层数上限',
    labelEn: 'code.run nesting depth limit',
    description: '限制单个顶层 cell 中 code.run 的最大嵌套层数。',
    descriptionEn: 'Limits the maximum code.run nesting depth within one top-level cell.',
  },
  {
    key: 'maxOutputBytes',
    type: 'integer',
    default: 64 * 1024 * 1024,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '单 cell 输出上限 (bytes)',
    labelEn: 'Output limit per cell (bytes)',
    description: '限制单个 cell 的日志和返回结果的合计大小。',
    descriptionEn: 'Limits the combined size of one cell\'s logs and returned result.',
  },
  {
    key: 'maxValueNodes',
    type: 'integer',
    default: 100_000,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '返回值节点数上限',
    labelEn: 'Returned-value node limit',
    description: '限制单次返回值的 Value Graph 节点数。',
    descriptionEn: 'Limits the Value Graph node count for one returned value.',
  },
  {
    key: 'maxValueEdges',
    type: 'integer',
    default: 1_000_000,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '返回值引用边数上限',
    labelEn: 'Returned-value reference-edge limit',
    description: '限制单次返回值的 Value Graph 引用边数。',
    descriptionEn: 'Limits the Value Graph reference-edge count for one returned value.',
  },
  {
    key: 'maxValueArrayLength',
    type: 'integer',
    default: 1_000_000,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '返回数组长度上限',
    labelEn: 'Returned-array length limit',
    description: '限制返回数组的最大声明长度。',
    descriptionEn: 'Limits the maximum declared length of a returned array.',
  },
  {
    key: 'maxValueBigIntDigits',
    type: 'integer',
    default: 100_000,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '返回值 BigInt 十进制位数上限',
    labelEn: 'Returned-value BigInt decimal-digit limit',
    description: '限制返回值中 BigInt 的十进制位数。',
    descriptionEn: 'Limits the decimal-digit count of BigInt values in one returned value.',
  },
  {
    key: 'tipCooldownMessages',
    type: 'integer',
    default: 3,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '同类恢复提示间隔 (messages)',
    labelEn: 'Same-kind recovery tip interval (messages)',
    description: '同类恢复提示之间的最小间隔。',
    descriptionEn: 'The minimum gap between recovery tips of the same kind.',
  },
  {
    key: 'tipEscalationFailures',
    type: 'integer',
    default: 2,
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    label: '详细恢复提示阈值 (failures)',
    labelEn: 'Detailed recovery tip threshold (failures)',
    description: '连续失败达到此次数后显示更详细的恢复提示。',
    descriptionEn: 'After this many consecutive failures, a more detailed recovery tip is shown.',
  },
])

/** Presentation groups keep high-attention decisions separate from advanced policy and limits. */
export const CONFIG_GROUPS = Object.freeze([
  {
    key: 'core',
    label: '常用与兼容性',
    labelEn: 'Common and compatibility',
    fields: Object.freeze(['enabled', 'enhancedToolView', 'autoDescribeRunCode', 'canonicalizeToolCalls']),
  },
  {
    key: 'optional',
    label: '可选能力',
    labelEn: 'Optional capabilities',
    fields: Object.freeze(['cordisToolsEnabled']),
  },
  {
    key: 'advanced',
    label: '高级行为',
    labelEn: 'Advanced behavior',
    fields: Object.freeze([
      'looseTopLevelRedeclarations',
      'autoRewriteImports',
      'autoStripExports',
      'autoSplitRedeclarations',
      'durableReplay',
      'tipsEnabled',
    ]),
  },
  {
    key: 'limits',
    label: '资源限制',
    labelEn: 'Resource limits',
    fields: Object.freeze([
      'computeMs',
      'maxWallMs',
      'maxOldGenerationSizeMb',
      'maxNestedRunCodeDepth',
      'maxOutputBytes',
      'maxValueNodes',
      'maxValueEdges',
      'maxValueArrayLength',
      'maxValueBigIntDigits',
      'tipCooldownMessages',
      'tipEscalationFailures',
    ]),
  },
])

/** Resolved defaults, derived once from the field definitions. */
export const CONFIG_DEFAULTS = Object.freeze(
  Object.fromEntries(CONFIG_FIELDS.map(field => [field.key, field.default])),
)

/** Key of the runtime kill switch; all settings are applied live by the Host. */
export const ENABLED_KEY = 'enabled'
